### ISSUE TITLE
 Some doubts during the reproduction process.

### ISSUE THREAD

**Issue by xt-ai** [feiyuchen7/M3NET#2]
Hello, congratulations on completing and publishing your work! I'm interested in graph methods, so I want to reproduce this method. However, I encountered the following issues while trying to replicate it:

1.The feature dimensions in the provided file do not match those in the code.
2.Even after modifying the dimension settings in the code based on the feature file, I still can't run it successfully. The core components of the code, model_hyper.py and HypergraphConv.py, are throwing errors.

Could you please help me with these questions? I'm looking forward to your response.

**Comment by feiyuchen7** [comment]
Hi, what are the mismatched feature dimensions and what are the errors?

**Comment by xt-ai** [comment]
Hello, thank you for your response. The issue of mismatched feature dimensions is observed in the feature files, where the dimensions for the audio and text modalities are 300 (MELD) and 1582 (IEMOCAP) respectively, while the corresponding values in the code are 100 and 512. After modifying the dimensions in the code and running it, I encountered an error in the HypergraphConv.py file at line 151. It seems that it expected a value of 360 (I vaguely remember this number), but received 180 instead. Upon debugging, I found that the input was 180, while the parameters were defined as size=(num_edges, num_nodes) (360, 180). I changed it to size=(num_nodes, num_edges) and, after reviewing that section of the code, I realized that the output from line 148, out(180, 1, dim), needs to be reduced to (180, dim). After completing these modifications, some batches were successfully processed, but when passing certain batch data to model_hyper.py, I encountered a null value error at line 238. Upon debugging, I found that e_type was assigned a null value. Since this is a core code error, I am unable to identify the cause. I am looking forward to your clarification and guidance.

**Comment by xt-ai** [comment]
Hello, thank you for your response. The issue of mismatched feature dimensions is observed in the feature files, where the dimensions for the audio and text modalities are 300 (MELD), 1582 (IEMOCAP), and 342 (MELD/IEMOCAP), while the corresponding values in the code are 100 and 512. After modifying the dimensions in the code and running it, I encountered an error in the HypergraphConv.py file at line 151. It seems that it expected a value of 360 (I'm a bit unsure about this number, I somewhat forgot), but received 180 instead. Upon debugging, I found that the input was 180, while the parameters were given as size=(num_edges, num_nodes) (360, 180). I changed it to size=(num_nodes, num_edges) and, after reading that section of the code, I felt that the output from line 148, out(180, 1, dim), needs to be dimensionally reduced to (180, dim). After completing these modifications, some batches were able to run successfully, but for some batches, when the data is passed to line 238 of model_hyper.py, it reports a null value error. Upon debugging, I found that e_type is assigned a null value. Since this is an error in the core code, I am unable to identify the exact cause. I'm looking forward to your clarification and guidance.

**Comment by feiyuchen7** [comment]
Hi, I've double checked the feature files I provided.
The dimensions for the A/V/T modalities are 100/512/1024 (IEMOCAP) and 300/342/1024 (MELD). I've modified train.py to include dimensions on MELD.

Regarding the errors you mentioned in the HypergraphConv.py file, the output from line 148 has a size of (num_edges,1,dim) where num_edges is not fixed whose value is equal to that of the output from line 115. That is to say, the input dimension to line 151 is dynamically changing instead of being any fixed number. Moreover, with line 148 outputing (num_edges,1,dim), I didn't get any errors at line 151.

My best guess of your issues is that you may use a different version of torch_geometric and it might be worth a look.

**Comment by xt-ai** [comment]
Hello, based on your response, I have resolved the first two issues, but the third issue still remains. The error occurs when running the second batch. The error message is as follows:
/model_hyper.py:237: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matricesor `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2985.)
  t_type = torch.LongTensor(perm).T.cuda()
Traceback (most recent call last):
  File "train.py", line 495, in <module>
    train_loss, train_acc, _, _, train_fscore, _, _, _, _, _ = train_or_eval_graph_model(model, loss_function, train_loader, e, cuda, args.modals, optimizer, True, dataset=args.Dataset)
  File "train.py", line 206, in train_or_eval_graph_model
    log_prob, e_i, e_n, e_t, e_l = model([textf1,textf2,textf3,textf4], qmask, umask, lengths, acouf, visuf, epoch)
  File "/home/tugeng/miniconda3/envs/mmdfn2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/tugeng/xt/M3NET-main/M3NET-main/model.py", line 863, in forward
    emotions_feat = self.graph_model(features_a, features_v, features_l, seq_lengths, qmask, epoch)
  File "/home/tugeng/miniconda3/envs/mmdfn2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/tugeng/xt/M3NET-main/M3NET-main/model_hyper.py", line 156, in forward
    hyperedge_index, edge_index, features, batch, hyperedge_type1 = self.create_hyper_index(a, v, l, dia_len, self.modals)
  File "/data/tugeng/xt/M3NET-main/M3NET-main/model_hyper.py", line 238, in create_hyper_index
    e_type = torch.where(t_type[1]-t_type[0] > 0, 1, 0).cuda()
IndexError: index 1 is out of bounds for dimension 0 with size 0

**Comment by xt-ai** [comment]
Additional information: The error occurs in the MELD dataset, while the IEMOCAP dataset runs without any issues.

**Comment by feiyuchen7** [comment]
Hi, thank you for your information. There was a redundant piece of code in the model_hyper.py file. I've removed it and updated model_hyper.py.
