### ISSUE TITLE
Multi-frequency Graph construction problem

### ISSUE THREAD

**Issue by Julian075** [feiyuchen7/M3NET#3]
Hello, I'm trying to use your code, but I can't replicate your results. I downloaded your code and the dataset and used the code line that you gave on GitHub, but the metrics are different. Also, I have a problem finding the Multi-frequency Graph construction in the code. I would be grateful if you could help me.

**Comment by feiyuchen7** [comment]
Hi
model_hyper.py includes the codes for the multi-frequency graph construction (line 170).
We suggest that you can try different random seeds for better results. Some pre-trained checkpoints are also available.
