### ISSUE TITLE
Problem of reproducing results of IEMOCAP and MELD

### ISSUE THREAD

**Issue by AdventureStory** [feiyuchen7/M3NET#5]
Hello, congratulations on completing and publishing your work! I appreciate your excellent work on ERC task, so I want to reproduce this method. However, I couldn't reproduce the results of the IEMOCAP and MELD datasets mentioned in your paper.
Here is what I have done and the results I have got, I would appreciate if you could tell me what's wrong with my implementation.
1. download the feature files you offer and place it in proper position as set in dataloader.py:
<img width="354" alt="image" src="https://github.com/feiyuchen7/M3NET/assets/102843790/eb9219c2-d174-439f-a870-0e737e7fd146">
<img width="1167" alt="image" src="https://github.com/feiyuchen7/M3NET/assets/102843790/113b857c-6f7c-44eb-bc56-aab6936619d5">
<img width="1086" alt="image" src="https://github.com/feiyuchen7/M3NET/assets/102843790/a736393c-dc8d-45c2-9877-900e27e51090">

2. run the command you give in readme:
Here are the results of IEMOCA, which is much lower than the paper as it only achieves around 66 in acc and F1-score. And results of paper is about 72 in F1-score and acc.
<img width="1255" alt="image" src="https://github.com/feiyuchen7/M3NET/assets/102843790/8172df4a-cb98-4037-b495-5f3341f7e4fe">
<img width="1126" alt="image" src="https://github.com/feiyuchen7/M3NET/assets/102843790/12e53118-f47e-40cc-9b26-d5ae40dda14b">
Here are the results of MELD, which is much lower than the paper as it only achieves around 66 in acc and 65 in F1-score. And results of paper is about 67 in acc and 68 in F1-score.
<img width="1213" alt="image" src="https://github.com/feiyuchen7/M3NET/assets/102843790/ce9b42a3-a9c8-46f5-9e06-0dce567153fe">

**Comment by feiyuchen7** [comment]
Please see the latest update. The hyperparameters of numbers of graph layers are included in the command line arguments.
