### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by jellyfishovo** [feiyuchen7/M3NET#6]
Thank you for your impressive work!
I try to reproduce the result using your training example, while it reports "ValueError: Encountered tensor with size 2607 in dimension 0, but expected size 917." in line 150 in HypergraphConv.py, which is "out = self.propagate(hyperedge_index, x=out, norm=D, alpha=alpha,
size=(num_edges, num_nodes))" 
Then what should i do to fix it 
Thanks!!

**Comment by feiyuchen7** [comment]
Hi, it may be due to different torch-geometric versions.
