### ISSUE TITLE
复现出现的一些问题

### ISSUE THREAD

**Issue by 1136623363** [feiyuchen7/M3NET#7]
您好！我在尝试复现您的论文

按照您给出的参数设置
`python -u train.py --base-model 'GRU' --dropout 0.5 --lr 0.0001 --batch-size 16 --graph_type='hyper' --epochs=80 --graph_construct='direct' --multi_modal --mm_fusion_mthd='concat_DHT' --modals='avl' --Dataset='IEMOCAP' --norm BN --num_L=3 --num_K=4`
和指定的torch-geometric 版本1.7.2

在IEMOCAP数据集上，我得出的结果只达到了70.73，我也尝试过调整一些参数，例如use_modal、use_residue等，use_modal设置成True的话可以略微提高结果的accuracy，但是还是达不到论文的72，然后use_residue这个参数调整对结果没有明显的改变。

不知道是否哪里有遗漏，非常需要您的指点！拜托🙏
```
Namespace(no_cuda=False, base_model='GRU', graph_model=True, nodal_attention=True, windowp=10, windowf=10, lr=0.0001, l2=3e-05, rec_dropout=0.1, dropout=0.5, batch_size=16, epochs=80, class_weight=True, active_listener=False, attention='general', tensorboard=True, graph_type='hyper', use_topic=False, alpha=0.2, multiheads=6, graph_construct='direct', use_gcn=False, use_residue=False, multi_modal=True, mm_fusion_mthd='concat_DHT', modals='avl', av_using_lstm=False, Deep_GCN_nlayers=4, Dataset='IEMOCAP', use_speaker=True, use_modal=True, norm='BN', testing=False, num_L=3, num_K=4)
Running on GPU
construct hyper
Graph NN with GRU as base model.
<dataloader.IEMOCAPDataset object at 0x000001C9ED8ADF00>
```
![image](https://github.com/feiyuchen7/M3NET/assets/72068332/cb35d07b-83c0-4b69-a018-cc4ec3d825f3)

**Comment by feiyuchen7** [comment]
您好，在不同的机器（GPU/CPU等）上结果会有波动，您可以尝试下不同的随机种子，或者在当前种子下微调lr、dropout、norm、L和K值。我们也给出了我们训练的几个checkpoints。

**Comment by 1136623363** [comment]
您好，我对您的这篇论文非常感兴趣！
```
@inproceedings{chen2023multivariate,
  title={Multivariate, Multi-Frequency and Multimodal: Rethinking Graph Neural Networks for Emotion Recognition in Conversation},
  author={Chen, Feiyu and Shao, Jie and Zhu, Shuyuan and Shen, Heng Tao},
  booktitle={Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition},
  pages={10761--10770},
  year={2023}
}
```
您在该论文中，所提出的将基于超图的多元传播和基于普通图的多频传播的双通道并行理念让我耳目一新。

但是，针对您给出的代码，我有几点疑惑

1. weight：在model_hyper.py的[155行](https://github.com/feiyuchen7/M3NET/blob/4d0fa88cd4f92c72b053527e877763f54e29ccb2/model_hyper.py#L155)中，您定义了一个weight,其用于HypergraphConv.py中计算节点的度B

2. EW_weight：在model_hyper.py的[156行](https://github.com/feiyuchen7/M3NET/blob/4d0fa88cd4f92c72b053527e877763f54e29ccb2/model_hyper.py#L156)中，您定义了一个EW_weight,其用于HypergraphConv.py中计算超边的度D

但是以上两个变量，均被设置成了固定的1，
![image](https://github.com/feiyuchen7/M3NET/assets/72068332/827428ad-0ed6-447f-8c42-c84aff2cdbd1)

那是否与论文3.2.1中的Weights的随机设定相悖
![image](https://github.com/feiyuchen7/M3NET/assets/72068332/b91f3e68-2ec2-467d-b97a-5e368012e0a6)

并且我在后续中未找到调整这些参数的代码部分。如果权重没有调整，那超边的构建方法是否过于简单

我是一个ERC领域的初学者，如果能得到您的点拨，我将不胜感激！

**Comment by 1136623363** [comment]
两个weight都会更新，抱歉，我的问题！
